volumes:
  data:
  media:
  export:
  consume:
  pgdata:
  redisdata:
  ollama:

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
      - .:/usr/src/paperless-ngx-scripts
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

      PAPERLESS_SCRIPTS_TOKEN: c5e9b4524d79295f6be0903c29f72e9cba791040
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless-ngx-scripts/post-consume.sh
      PAPERLESS_POST_CONSUME_SCRIPT_NAMES: ping,autotitle-ai
      PAPERLESS_POST_CONSUME_SCRIPT_AUTOTITLE_OPENAI_BASE_URL: http://ollama:11434
      PAPERLESS_POST_CONSUME_SCRIPT_AUTOTITLE_OPENAI_MODEL: llama3.2:3b

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    environment:
      OLLAMA_KEEP_ALIVE: 15m
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 1m
      timeout: 10s
      retries: 3

  ollama-run:
    depends_on:
      ollama:
        condition: service_healthy
    image: ollama/ollama:latest
    command: pull llama3.2:3b
    environment:
      OLLAMA_HOST: ollama:11434
